language: node_js
node_js:
- lts/*
script: npm run test
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: thibault.maekelbergh@icloud.com
  api_key:
    secure: jQTBVJttav2U2+K05hhLQ8X1PiSXhtD8sSQ+c4dBk0/N/lV0rM7DULZvaKlpUa2h9yyPIeX/lBj4dyZ9oW58c6jQtSvehBkkXUqXRr4Ha9Hvj6GIKSXeoK7yS/pw0vnRq53wawMERTJ6F2xQW2KVdpEYDeY5GVPpADZeAk2dE9mEPilkybEh+IzHwyJlWYYiqo0xmfeU84tuOl1SZaoRqUSvkU1HIA58l6oFJcTdyZfRHLCRaZ6JWUe98OyquRM6msJnxQFuWHucgaK0764F0Qvb6tS0HifDvfzdUCbRx4FO1pYjLSuDVuDjc6rGILWparSB7aptUQAOWpYcfnqVRM66M6KP9Ysj9x2Crr54s9fdnyL+lk0T8lzvEGuzxXLqKYOThj9YaIuW95S2BoqNsvT6SQ62aoohKFf8fS2VjdKRCAFrSfhaOdK0X7qcIpk7H3m1mMEMqtdPOh7b2kRPHu0V0RrR9kMbuwN1pfhhokZpZpvkDuHn2bkPN/XgtW1flRHCCg671iZDkbt6nOV6T77SliyGMbOpL0nKyUDh/KYK6VCwLHPFIDVxi0HtoiAE9WBUlnR6xONId+lUuPSRUYCpNia0ilVuBettghJ3MUXpM2TeLhRr/qQuTpc6tBQaytv4ulXhfM4bfGG69Q41pxicC6GM5mwsi6cV5Fz1ncw=
  on:
    tags: true
    repo: thibmaek/pure-fun
